### ISSUE TITLE
Compiling this on Raspberry Pi is... quite hard.

### ISSUE THREAD

**Issue by JeanMarcZimmer** [tostc/libDiscordBot#9]
### Lib dependency Opus:
one of the dependencies, Opus, doesn't immediately compile on Raspberry. It needs the `-DOPUS_DISABLE_INTRINSICS=ON` option when generating the CMake files in `libDiscordBot/build`
You can read the entire struggle of finding the solution here : https://github.com/xiph/opus/issues/203

### Compiling the bot with the lib:
On Raspberry Pis, the default Atomic standard library doesn't include the call `__atomic_fetch_add_8`. To compile the bot, the linker option `-latomic` had to be added. I modified the CMakeLists.txt file as indicated below, following [this](https://stackoverflow.com/a/11797272/9950378) StackOverflow answer, but I'm not sure at all if it's a good way to do it.
``` CMakeLists
set(GCC_COVERAGE_LINK_FLAGS "-latomic")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${GCC_COVERAGE_LINK_FLAGS}")
```

This is not a big deal, but I think it could be of interest to you.

**Comment by xnorpx** [comment]
Added: https://gitlab.xiph.org/xiph/opus/-/issues/2343 to track neon issue on rp

**Comment by tostc** [comment]
Hi,

thanks for reporting. I will add these fix.

**Comment by tostc** [comment]
I've added your fix.
